<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ProductoSoda;
use App\Models\Ticket;

class ExactusSeeder extends Seeder
{
    public function run(): void
    {
        // ── PRODUCTOS SODA (SOD/sod) ──────────────────────────────────────────
        $productosSoda = [
            ['codigo' => 'SOD-00002', 'nombre' => 'ALBOROTO',                             'precio' => 200],
            ['codigo' => 'SOD-00003', 'nombre' => 'CONITOS JACKS',                        'precio' => 200],
            ['codigo' => 'SOD-00004', 'nombre' => 'CENTAVITOS',                           'precio' => 200],
            ['codigo' => 'SOD-00005', 'nombre' => 'CHEETOS',                              'precio' => 400],
            ['codigo' => 'SOD-00008', 'nombre' => 'CHIRULITOS',                           'precio' => 450],
            ['codigo' => 'SOD-00010', 'nombre' => 'LAYS',                                 'precio' => 450],
            ['codigo' => 'SOD-00015', 'nombre' => 'PAPIOLAS',                             'precio' => 450],
            ['codigo' => 'SOD-00017', 'nombre' => 'PLATANOS',                             'precio' => 350],
            ['codigo' => 'SOD-00019', 'nombre' => 'PALOMITA MIXTA',                       'precio' => 500],
            ['codigo' => 'SOD-00022', 'nombre' => 'QUESITOS',                             'precio' => 450],
            ['codigo' => 'SOD-00023', 'nombre' => 'RANCHITAS',                            'precio' => 200],
            ['codigo' => 'SOD-00025', 'nombre' => 'TOCINITOS',                            'precio' => 200],
            ['codigo' => 'SOD-00027', 'nombre' => 'JALAPEÑAS',                            'precio' => 200],
            ['codigo' => 'SOD-00030', 'nombre' => 'TRONADITAS',                           'precio' => 450],
            ['codigo' => 'SOD-00032', 'nombre' => 'YUQUITAS',                             'precio' => 350],
            ['codigo' => 'SOD-00034', 'nombre' => 'BARRA CEREAL',                         'precio' => 450],
            ['codigo' => 'SOD-00036', 'nombre' => 'BEST',                                 'precio' => 150],
            ['codigo' => 'SOD-00038', 'nombre' => 'BLAK OUT',                             'precio' => 150],
            ['codigo' => 'SOD-00041', 'nombre' => 'CHOKIS CLASICA',                       'precio' => 500],
            ['codigo' => 'SOD-00042', 'nombre' => 'CHOKIS M/R',                           'precio' => 600],
            ['codigo' => 'SOD-00043', 'nombre' => 'GALLETA CLUB',                         'precio' => 300],
            ['codigo' => 'SOD-00046', 'nombre' => 'FLORENTINA',                           'precio' => 500],
            ['codigo' => 'SOD-00047', 'nombre' => 'GALLETA MANTEQUILLA',                  'precio' => 250],
            ['codigo' => 'SOD-00048', 'nombre' => 'GALLETA QUAKER',                       'precio' => 400],
            ['codigo' => 'SOD-00051', 'nombre' => 'YIPY',                                 'precio' => 300],
            ['codigo' => 'SOD-00052', 'nombre' => 'CHIKY',                                'precio' => 300],
            ['codigo' => 'SOD-00055', 'nombre' => 'GALLETA MERENDINA CHOCO',              'precio' => 300],
            ['codigo' => 'SOD-00056', 'nombre' => 'MERENDINA VAINILLA',                   'precio' => 300],
            ['codigo' => 'SOD-00058', 'nombre' => 'SORBETO JACKS',                        'precio' => 300],
            ['codigo' => 'SOD-00059', 'nombre' => 'SORBETO CHOQUINO',                     'precio' => 300],
            ['codigo' => 'SOD-00061', 'nombre' => 'ANGELITOS',                            'precio' => 200],
            ['codigo' => 'SOD-00062', 'nombre' => 'BARQUILLOS COMBINADOS',                'precio' => 600],
            ['codigo' => 'SOD-00063', 'nombre' => 'BIANCHI',                              'precio' => 25],
            ['codigo' => 'SOD-00067', 'nombre' => 'BON O BON',                            'precio' => 250],
            ['codigo' => 'SOD-00068', 'nombre' => 'BOTONETAS MENTAS',                     'precio' => 100],
            ['codigo' => 'SOD-00072', 'nombre' => 'CHOCOLITO',                            'precio' => 350],
            ['codigo' => 'SOD-00074', 'nombre' => 'CONFITE MENTA',                        'precio' => 25],
            ['codigo' => 'SOD-00083', 'nombre' => 'MYM CHOCOLATE',                        'precio' => 900],
            ['codigo' => 'SOD-00084', 'nombre' => 'HIPO',                                 'precio' => 300],
            ['codigo' => 'SOD-00086', 'nombre' => 'PALITO DE LECHE',                      'precio' => 100],
            ['codigo' => 'SOD-00089', 'nombre' => 'POPI SURTIDO',                         'precio' => 100],
            ['codigo' => 'SOD-00093', 'nombre' => 'TUTTO',                                'precio' => 550],
            ['codigo' => 'SOD-00111', 'nombre' => 'KERNS',                                'precio' => 700],
            ['codigo' => 'SOD-00113', 'nombre' => 'PEPSI',                                'precio' => 700],
            ['codigo' => 'SOD-00114', 'nombre' => 'JUGO DEL VALLE',                       'precio' => 600],
            ['codigo' => 'SOD-00115', 'nombre' => 'TROPICAL PEQUEÑO',                     'precio' => 500],
            ['codigo' => 'SOD-00122', 'nombre' => 'HALLS',                                'precio' => 450],
            ['codigo' => 'SOD-00125', 'nombre' => 'ALOE VERA',                            'precio' => 1150],
            ['codigo' => 'SOD-00128', 'nombre' => 'NIEVE Y BOLI HELADO',                  'precio' => 200],
            ['codigo' => 'SOD-00133', 'nombre' => 'YUPIS',                                'precio' => 250],
            ['codigo' => 'SOD-00135', 'nombre' => 'RODITAS',                              'precio' => 300],
            ['codigo' => 'SOD-00140', 'nombre' => 'PINGUINOS BIMBO',                      'precio' => 850],
            ['codigo' => 'SOD-00141', 'nombre' => 'BIGOTES/ CUPCAKES BIMBO',              'precio' => 650],
            ['codigo' => 'SOD-00144', 'nombre' => 'JUGO DUCAL',                           'precio' => 400],
            ['codigo' => 'SOD-00145', 'nombre' => 'GASEOSAS 355 ML',                      'precio' => 750],
            ['codigo' => 'SOD-00146', 'nombre' => 'GASEOSAS 600 ML',                      'precio' => 1150],
            ['codigo' => 'SOD-00147', 'nombre' => 'TROPICAL',                             'precio' => 750],
            ['codigo' => 'SOD-00148', 'nombre' => 'PAWERADE',                             'precio' => 1250],
            ['codigo' => 'SOD-00149', 'nombre' => 'HI-C',                                 'precio' => 600],
            ['codigo' => 'SOD-00153', 'nombre' => 'PIZEROLAS',                            'precio' => 450],
            ['codigo' => 'SOD-00154', 'nombre' => 'CONFITE DAMY',                         'precio' => 50],
            ['codigo' => 'SOD-00155', 'nombre' => 'SNICKERS 50 G',                        'precio' => 800],
            ['codigo' => 'SOD-00161', 'nombre' => 'GOMITAS MANGO O SANDIA',               'precio' => 150],
            ['codigo' => 'SOD-00163', 'nombre' => 'TRULULU TIRA',                         'precio' => 150],
            ['codigo' => 'SOD-00164', 'nombre' => 'PALETA MANGO, SANDIA, MANGO CON TAJIN','precio' => 100],
            ['codigo' => 'SOD-00166', 'nombre' => 'FRESCO LECHE',                         'precio' => 700],
            ['codigo' => 'SOD-00180', 'nombre' => 'HELADO CREMORIN',                      'precio' => 250],
            ['codigo' => 'SOD-00181', 'nombre' => 'SUPER CONO',                           'precio' => 850],
            ['codigo' => 'SOD-0182',  'nombre' => 'CHOCO MAX',                            'precio' => 900],
            ['codigo' => 'SOD-00185', 'nombre' => 'TAKIS',                                'precio' => 550],
            ['codigo' => 'SOD-00186', 'nombre' => 'CHAO',                                 'precio' => 150],
            ['codigo' => 'SOD-00187', 'nombre' => 'EVERVEST',                             'precio' => 1150],
            ['codigo' => 'SOD-00188', 'nombre' => 'MANGO',                                'precio' => 1000],
            ['codigo' => 'SOD-00189', 'nombre' => 'COPO CON HELADO',                      'precio' => 1500],
            ['codigo' => 'SOD-00190', 'nombre' => 'COPO',                                 'precio' => 1000],
            ['codigo' => 'SOD-00191', 'nombre' => 'TROPICAL CAJA',                        'precio' => 450],
            ['codigo' => 'SOD-00192', 'nombre' => 'LOMONCHO FRASCO',                      'precio' => 400],
            ['codigo' => 'SOD-00193', 'nombre' => 'LIMONCHO SOBRE',                       'precio' => 100],
            ['codigo' => 'SOD-00194', 'nombre' => 'FRIJOLI',                              'precio' => 150],
            ['codigo' => 'SOD-00195', 'nombre' => 'CRONCHITO',                            'precio' => 200],
            ['codigo' => 'SOD-00196', 'nombre' => 'FRESITA EN POLVO',                     'precio' => 200],
            ['codigo' => 'SOD-00197', 'nombre' => 'ZIBAS',                                'precio' => 700],
            ['codigo' => 'SOD-00198', 'nombre' => 'GALLETA JUMBO',                        'precio' => 150],
            ['codigo' => 'SOD-00199', 'nombre' => 'GELATINA EN BOLI',                     'precio' => 200],
            ['codigo' => 'SOD-00200', 'nombre' => 'CHOCOLATE BIANCHI',                    'precio' => 300],
            ['codigo' => 'SOD-00201', 'nombre' => 'HELADO PAQUITA',                       'precio' => 450],
            ['codigo' => 'SOD-00202', 'nombre' => 'BARQUILLOS CHOCOLATE',                 'precio' => 850],
            ['codigo' => 'SOD-00203', 'nombre' => 'PALOMITAS CARAMELO',                   'precio' => 1000],
            ['codigo' => 'SOD-00204', 'nombre' => 'PALOMITAS MANTEQUILLA',                'precio' => 1000],
            ['codigo' => 'SOD-00205', 'nombre' => 'ALFAJOR BLANCO',                       'precio' => 600],
            ['codigo' => 'SOD-00206', 'nombre' => 'ALFAJOR AMARILLO',                     'precio' => 600],
            ['codigo' => 'SOD-00215', 'nombre' => 'NESTLE PEQUEÑO',                       'precio' => 700],
            ['codigo' => 'SOD-00216', 'nombre' => 'NESTLE GRANDE',                        'precio' => 1400],
            ['codigo' => 'SOD-00220', 'nombre' => 'QUEQUE CHOCOLATE',                     'precio' => 500],
            ['codigo' => 'SOD-00221', 'nombre' => 'QUEQUE SECO',                          'precio' => 400],
            ['codigo' => 'SOD-00222', 'nombre' => 'ENCHILADAS',                           'precio' => 550],
            ['codigo' => 'SOD-00223', 'nombre' => 'PALO QUESO',                           'precio' => 350],
            ['codigo' => 'SOD-00224', 'nombre' => 'CACHOS',                               'precio' => 550],
            ['codigo' => 'SOD-00225', 'nombre' => 'ALFAJOR',                              'precio' => 250],
            ['codigo' => 'SOD-00226', 'nombre' => 'PIZZA',                                'precio' => 1500],
            ['codigo' => 'SOD-00227', 'nombre' => 'CANGREJO',                             'precio' => 550],
            ['codigo' => 'SOD-00230', 'nombre' => 'PAÑUELOS',                             'precio' => 550],
            ['codigo' => 'SOD-00238', 'nombre' => 'PORCION DEL DIA',                      'precio' => 1650],
            ['codigo' => 'SOD-00245', 'nombre' => 'DONAS',                                'precio' => 600],
            ['codigo' => 'SOD-00246', 'nombre' => 'MANI SALADO',                          'precio' => 550],
            ['codigo' => 'SOD-00247', 'nombre' => 'SKITLES ORI',                          'precio' => 1000],
            ['codigo' => 'SOD-00248', 'nombre' => 'SKITLES BERRY',                        'precio' => 1000],
            ['codigo' => 'SOD-00249', 'nombre' => 'SKITLES TROPICAL',                     'precio' => 1000],
            ['codigo' => 'SOD-00250', 'nombre' => 'MANI GARAPIÑADO',                      'precio' => 750],
            ['codigo' => 'SOD-00251', 'nombre' => 'SEMILLA MIXTA',                        'precio' => 1000],
            ['codigo' => 'SOD-00253', 'nombre' => 'LUCAS MUECAS CEREZA',                  'precio' => 550],
            ['codigo' => 'SOD-00254', 'nombre' => 'LUCAS MUECAS CHAMOY',                  'precio' => 550],
            ['codigo' => 'SOD-00255', 'nombre' => 'LUCAS MUECAS PEPINO',                  'precio' => 550],
            ['codigo' => 'SOD-00257', 'nombre' => 'SWINKLES SALSAGUETI',                  'precio' => 1200],
            ['codigo' => 'SOD-00258', 'nombre' => 'YOGURT FRUTAS',                        'precio' => 1100],
            ['codigo' => 'SOD-00259', 'nombre' => 'YOGURT FRESA',                         'precio' => 1100],
            ['codigo' => 'SOD-00260', 'nombre' => 'YOGURT TOPPING FRESA',                 'precio' => 1500],
            ['codigo' => 'SOD-00261', 'nombre' => 'YOGURT GRANOLA Y FRESA',               'precio' => 1500],
            ['codigo' => 'SOD-00262', 'nombre' => 'YOGURT FRESA',                         'precio' => 1100],
            ['codigo' => 'SOD-00263', 'nombre' => 'YOGURT FRESA LULA',                    'precio' => 1100],
            ['codigo' => 'SOD-00264', 'nombre' => 'HELADO ARTESANAL',                     'precio' => 800],
            ['codigo' => 'SOD-00265', 'nombre' => 'FRESAS CON CREMA',                     'precio' => 1950],
            ['codigo' => 'SOD-00266', 'nombre' => 'VASO CON MANGO',                       'precio' => 2000],
        ];

        foreach ($productosSoda as $item) {
            ProductoSoda::create([
                'nombre'          => ucfirst(strtolower($item['nombre'])),
                'codigo_softland' => $item['codigo'],
                'codigo_barras'   => null,
                'precio'          => $item['precio'],
                'activo'          => true,
            ]);
        }

        // ── TIQUETES (COM/com) — categoria_d = 1 (Cocina) ────────────────────
        $tiquetes = [
            ['codigo' => 'COM-00277', 'nombre' => 'GUARNI',            'precio' => 750],
            ['codigo' => 'COM-00281', 'nombre' => 'ALMUERZO ECONOMICO','precio' => 1500],
            ['codigo' => 'COM-00282', 'nombre' => 'ALMUERZO TARDE',    'precio' => 3300],
            ['codigo' => 'COM-00283', 'nombre' => 'SALCHIPAPAS',       'precio' => 1000],
            ['codigo' => 'COM-00284', 'nombre' => 'PORCION HUEVO',     'precio' => 750],
            ['codigo' => 'COM-00285', 'nombre' => 'PORCION PINTO',     'precio' => 1000],
            ['codigo' => 'COM-00286', 'nombre' => 'TORTILLA ALIÑIADA', 'precio' => 1000],
            ['codigo' => 'COM-00287', 'nombre' => 'TORTILLA',          'precio' => 750],
            ['codigo' => 'COM-00288', 'nombre' => 'PORCION PLATANO',   'precio' => 150],
        ];

        foreach ($tiquetes as $item) {
            Ticket::create([
                'nombre'      => ucfirst(strtolower($item['nombre'])),
                'codigo'      => $item['codigo'],
                'categoria_d' => 1,
                'precio'      => $item['precio'],
            ]);
        }
    }
}
